# -*- coding: utf-8 -*-
"""Automatic Speech Recognition and Machine Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nk3T3BsClPI88fEm0Ye0c7JcY96UuTcr

# Downloading the libraries and softwares
"""

pip install SpeechRecognition
pip install pydub
apt-get install ffmpeg

pip install transformers
pip install torch

"""# ASR"""

import speech_recognition as sr
from pydub import AudioSegment
import os

recognizer = sr.Recognizer()

def recognize_speech_from_audio_file(file_path):
    audio = AudioSegment.from_file(file_path)
    audio.export("converted.wav", format="wav")

    with sr.AudioFile("converted.wav") as source:
        audio_data = recognizer.record(source)
        try:
            text_query = recognizer.recognize_google(audio_data)
            print("You said:", text_query)
            return text_query
        except sr.UnknownValueError:
            print("Sorry, I could not understand the audio.")
            return None
        except sr.RequestError as e:
            print("Could not request results; {0}".format(e))
            return None

# Upload the audio file
from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
    print(f'Processing file: {filename}')
    text_query = recognize_speech_from_audio_file(filename)

    # Write recognized text to a file
    with open("recognized_text.txt", "w") as file:
        file.write(text_query)

"""# Machine Translation using IndicNLP library"""

from transformers import pipeline
import torch

translator = pipeline(task="translation", model="facebook/nllb-200-distilled-600M", torch_dtype=torch.bfloat16)

with open("recognized_text.txt", "r") as file:
    recognized_text = file.read()

text=print(recognized_text)

recognized_text

text_translated = translator(recognized_text, src_lang="eng_Latn", tgt_lang="asm_Beng")
translated=(text_translated)

print(translated)

text_translated2 = translator(str(translated), src_lang="asm_Beng", tgt_lang="hin_Deva")
print(text_translated2)